- try git actions with the aim to replace travis-ci

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -13,15 +13,8 @@ jobs:
   default:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v2
-    - name: Check curl
-      run: curl --version
-    - name: Check lcov
-      run: |
-        wget http://downloads.sourceforge.net/ltp/lcov-1.14.tar.gz
-        tar xvfz lcov-1.14.tar.gz
-        make -C lcov-1.14
-        lcov-1.14/bin/lcov --version
+    - name: Test
+      run: echo Test
     #- name: make distcheck
     #  run: make distcheck
   
@@ -114,3 +107,29 @@ jobs:
         CXX: clang++-11
         CXXFLAGS: -std=c++20
       run: make -j check
+  
+  ##############################################################################
+  # codecov
+
+  gcc-8:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v1
+    - name: Setup
+      run: |
+        sudo apt-get update
+        sudo apt-get install gcc-8 g++-8
+    - name: Check
+      env:
+        CXX: g++-8
+        CXXFLAGS: -std=c++17
+      run: make -j check
+    - name: Coverage
+      run: |
+        wget http://downloads.sourceforge.net/ltp/lcov-1.14.tar.gz
+        tar xvfz lcov-1.14.tar.gz
+        make -C lcov-1.14
+        lcov-1.14/bin/lcov --gcov-tool gcov-8 -c -d . -o cov.info
+        lcov-1.14/bin/lcov -e cov.info '*/cxon/*.hxx' -o cxon.info 
+        lcov-1.14/bin/lcov -l cxon.info
+        bash <(curl -s https://codecov.io/bash) -f cxon.info || echo "upload failed"
